### PR TITLE
feat: Reticule

### PR DESCRIPTION
**Pull request by shirakaba**
> In terms of feel, my preference is something very simple and friendly. For example, the "10ten" naming / logo refers to two dots so if we can use a simple dot in the top-left to indicate where we're looking, that would be fine I think. Maybe it could even just be two dots: a big one that is the touch target, and a little one in the top left that is the dumbed-down reticule?

I thought it may be hard for a user to see a single dot (and if the dot were made bigger, it would start to obscure the underlying text), so I thought I'd get the ball rolling with this dotted line. I have also made the puck more circular.

## When not being dragged

Not much to say:

image

## When being dragged

No difference to spot from before; just wanted to show that the underlying text is still readable.

image

---

There is also scope to iterate on this. For example, showing the reticule only while the puck is in motion. Or make the dotted line transparent. Or do some other design. Anyway, I think this PR is a good start to build upon, at least.

One thing I must note now that the reticule is added – my thumb is way bigger than 50 x 50 px, so it may be nice in a future iteration if we could offset the reticule rather at least twice as far so that I can actually see what I'm aiming at.

- [x] Merge #4, which this PR branches off from.

### CODE REVIEW

**Comment by shirakaba** [comment]
> One thing I must note now that the reticule is added – my thumb is way bigger than 50 x 50 px, so it may be nice in a future iteration if we could offset the reticule rather at least twice as far so that I can actually see what I'm aiming at.

I made some adjustments to offset the reticule some more, and it certainly improves the ergonomics greatly. However, it also highlighted another problem.

https://user-images.githubusercontent.com/14055146/124399864-4c0ef600-dd16-11eb-8391-f0912621ea2a.mp4

If the reticule is in the top-left, then you can't look up words on the right-most edge of the page. Same for vice-versa. Even if you put the reticule in the top-centre, then there will be words at the edges of the page that you simply can't reach.

... This is a bit of a spanner in the works. I can only immediately think of two solutions (neither of them great):

1. tapping the puck flips the reticule horizontally, or;
2. as you approach the edge of the viewport, the reticule drifts.

I think 1) would be rather hard to explain to users, and I certainly wouldn't want to be tapping the reticule on every single line.

2) seems a bit easier to stomach, as it would be fully automatic. Just a bit fiddly to implement. We'd probably change the puck to a crosshair (as it's symmetrical) or I-bar, rather than an arrow-point, if we were to take this approach.

**Comment by shirakaba** [comment]
I think I'll turn this PR into a draft for the time being, as the current arrow-point has the mentioned edge-of-viewport limitation.

**Comment by shirakaba** [comment]
The drifting reticule approach actually really works! I'm sure it can be styled better than this, but I'm happy that I can now reach the edges and it's all automatic and (dare I say) intuitive!

https://user-images.githubusercontent.com/14055146/124400788-16b9d680-dd1d-11eb-9da3-420f046109b1.mp4

**Comment by birtles** [comment]
Thanks for this! Yes, I definitely agree with the drifting approach. I was also thinking the same thing. In my imagination if we had two dots the second smaller dot would move around the larger dot as you moved it across the screen.

Just watching the video I find the offset a little too much and the reticule too hard to notice. Did you turn off text highlighting in your videos or is it just not working?

I think if we highlighted the selected text it might be easier to follow. That said, the text highlighting is a bit awkward on iOS because it can trigger the selection menu. Fortunately there is an API designed just for this case, the [CSS Custom Highlight API](https://drafts.csswg.org/css-highlight-api-1/). It should be in Safari Tech Preview 99 ([release notes](https://developer.apple.com/safari/technology-preview/release-notes/)) but I don't know that it's any release version of Safari yet. Chrome have an [intent to prototype](https://groups.google.com/a/chromium.org/g/blink-dev/c/Ix2u8NHG5Po) but [Firefox haven't committed to it yet](https://github.com/mozilla/standards-positions/issues/482). So we'd need to conditionally support it but if it's coming to iOS soon, that might be enough for this case.

**Comment by birtles** [comment]
> I thought it may be hard for a user to see a single dot (and if the dot were made bigger, it would start to obscure the underlying text), so I thought I'd get the ball rolling with this dotted line. I have also made the puck more circular.

I think I was imagining something of the following proportions:



Alternatively, I think adding a "beak" / "arrow" like your original prototype could work if we make it translucent and rotate as needed?

That said, unlike you, I haven't actually tried it on a real device so I am just guessing. It _looks_ like the reticule is offset too far (and I'm a little concerned that will make targetting text at the bottom of the page difficult) but that's just a guess from looking.

**Comment by shirakaba** [comment]
Think I'm out of time for tonight to answer everything, so I'll get to the rest of these questions another day this week!

But briefly: I agree a small-circle + big-circle thing would be cool. We could apply vertical drift of some sort as well to help look up words at the bottom of the page – think I'd have to try it out to understand whether it's user-friendly or not, though.

**Comment by birtles** [comment]
> But briefly: I agree a small-circle + big-circle thing would be cool. We could apply vertical drift of some sort as well to help look up words at the bottom of the page – think I'd have to try it out to understand whether it's user-friendly or not, though.

Yes, I wondered about that too. I'm not sure yet if it will work for the vertical case but we can definitely give it a try!

**Comment by shirakaba** [comment]
> Just watching the video I find the offset a little too much and the reticule too hard to notice. Did you turn off text highlighting in your videos or is it just not working?

I've not turned off text highlighting. The only reason it was highlighting anything at all in the previous `feat/puck-safe-area` video was that I was long-pressing and dragging to coerce the puck into moving without scrolling the screen, and so the text highlighting came along for the ride. We can look into whether it's possible to force text to highlight, and whether it offers a superior user experience (I'm not so sure, as UIMenuController may start poking its head out and overlapping with the popup).

> I think if we highlighted the selected text it might be easier to follow. That said, the text highlighting is a bit awkward on iOS because it can trigger the selection menu. Fortunately there is an API designed just for this case, the CSS Custom Highlight API. It should be in Safari Tech Preview 99 (release notes) but I don't know that it's any release version of Safari yet. Chrome have an intent to prototype but Firefox haven't committed to it yet. So we'd need to conditionally support it but if it's coming to iOS soon, that might be enough for this case.

Interesting. I'll test whether the Safari on the latest iOS 15 beta supports it...

**Comment by shirakaba** [comment]
> Interesting. I'll test whether the Safari on the latest iOS 15 beta supports it...

Seems not ☹️ Here are the results of running some JS snippets in a Web Inspector connected to my iPhone (on iOS 15 beta 2) running Safari.

image

So the next thing to look into is how the genuine text range selection API handles.

**Comment by shirakaba** [comment]
I'm not having any luck using the Selection API on iOS Safari, either:

```js
// Where $0 is the element <b>Raem Shaquille Sterling</b>
const range = new Range();
range.setStart($0.firstChild, 0);
range.setEnd($0.firstChild, 4);
document.getSelection().addRange(range);
```

It doesn't produce a selection box on screen at all, and `document.getSelection()` returns an `<a class="image">` that I haven't even tapped on.

I remember years ago failing to get anything useful out of the Selection API at all on iOS Safari when trying to remove the `<rt>` tags from a selection made across a `<ruby>` element. I'm not totally surprised that it's doing nothing nowadays either.

(I may simply be using it incorrectly, mind).

**Comment by shirakaba** [comment]
> Alternatively, I think adding a "beak" / "arrow" like your original prototype could work if we make it translucent and rotate as needed?

I'm not looking forward to figuring out the CSS for that! But I did like the dotted lines in the original prototype too, so if we could figure out how to reimplement them for the big-puck-little-puck model (which is more complicated than the original due to having drift and and offset), I'd be all for it.

> That said, unlike you, I haven't actually tried it on a real device so I am just guessing. It looks like the reticule is offset too far (and I'm a little concerned that will make targetting text at the bottom of the page difficult) but that's just a guess from looking.

It feels fine in usage, but equally there may be a wide range of acceptable offsets. I think the reason I ended up with this offset is because the popup doesn't make any effort to get out of the way of the puck – when I used a y-offset close to zero, the popup would very often place the first dictionary result straight under my thumb (as, for horizontal texts, it prefers to lay out below the pointermove point – which is understandable, as it saves you from losing your place in the paragraph), preventing me from reading it without lifting my thumb away. In practice, I tend to keep my thumb on the puck to look up a series of words one after the other, so this may need re-assessing.

**Comment by birtles** [comment]
> Seems not ☹️ Here are the results of running some JS snippets in a Web Inspector connected to my iPhone (on iOS 15 beta 2) running Safari.

Right. I had a go with this in Safari Tech Preview (after enabling 'Highlight API' from the Develop → Experimental Features menu) and while I got it to not error, I couldn't get it to render anything using:

```js
var range = new StaticRange({ startContainer: $0, startOffset: 0, endContainer: $0, endOffset: 3 });
CSS.highlights.set('highlight', new Highlight(range));
document.styleSheets[0].insertRule(':root::highlight(example) { background-color: yellow }');
```

**Comment by birtles** [comment]
> I'm not having any luck using the Selection API on iOS Safari, either

It works for me in the simulator but I haven't tried on a real device:

スクリーンショット 2021-07-08 10 00 31

**Comment by birtles** [comment]
> It works for me in the simulator but I haven't tried on a real device:

That said, we should already be setting the text selection:

https://github.com/birchill/10ten-ja-reader/blob/248a5e4a0a09d990eb2df680d74653ea5ed10514/src/content.ts#L759-L767

I noticed when I was using the simulator previously the selection would be set at least sometimes.

**Comment by birtles** [comment]
> > Alternatively, I think adding a "beak" / "arrow" like your original prototype could work if we make it translucent and rotate as needed?
> 
> I'm not looking forward to figuring out the CSS for that! But I did like the dotted lines in the original prototype too, so if we could figure out how to reimplement them for the big-puck-little-puck model (which is more complicated than the original due to having drift and and offset), I'd be all for it.

I think it shouldn't be too bad (famous last words) but I'd like to try the big-puck-little-puck (aka earth-and-moon) part first.

I think it would be neat if the little puck (moon) maintained a consistent distance from the big puck (earth). To make that happen without having the user having to move their finger up and down slightly as they scan across the line we'd need to vertically center the two pucks on the touch/mouse point. I'm not sure how that would feel, but if that works, I think it would be easier to add lines between the two pucks if needed.

> I think the reason I ended up with this offset is because the popup doesn't make any effort to get out of the way of the puck – when I used a y-offset close to zero, the popup would very often place the first dictionary result straight under my thumb

Oh good point! Yes, we should add "tweak popup placement" to our list of things to cover. The heuristic for placing the popup should probably tack into account the visibility/position of the puck.

**Comment by birtles** [comment]
> I think it would be neat if the little puck (moon) maintained a consistent distance from the big puck (earth). To make that happen without having the user having to move their finger up and down slightly as they scan across the line we'd need to vertically center the two pucks on the touch/mouse point. I'm not sure how that would feel, but if that works, I think it would be easier to add lines between the two pucks if needed.

I had a go at doing this over in the [`feat/puck-earth-and-moon` branch](https://github.com/shirakaba/10ten-ja-reader/commits/feat/puck-earth-and-moon) based on the code in this PR: https://github.com/shirakaba/10ten-ja-reader/commit/538ef5bf4531a7b3661a0d126335fbb9f7841908

I didn't do the additional vertical centering because I'm not sure it's needed.

https://user-images.githubusercontent.com/1232595/124859467-f32bb000-dfea-11eb-86be-42b5db390199.mp4

**Comment by shirakaba** [comment]
> I think it shouldn't be too bad (famous last words) but I'd like to try the big-puck-little-puck (aka earth-and-moon) part first.

I love it! Looks way better than a dotted I-bar. Looks more friendly and less 1337.

> I think it would be neat if the little puck (moon) maintained a consistent distance from the big puck (earth). To make that happen without having the user having to move their finger up and down slightly as they scan across the line we'd need to vertically center the two pucks on the touch/mouse point. I'm not sure how that would feel, but if that works, I think it would be easier to add lines between the two pucks if needed.

I do like the idea of an orbit conceptually, but I'm not following how we'd avoid users having to move their finger up/down whilst scanning along the line. That is to say, if we did vertically center the pucks at the touch/mouse point, we'd lose the drifting effect, and thus lose the ability to define items on the very left/right sides of the screen.

**Comment by shirakaba** [comment]
I rebased all the puck work onto `main` and rebased your earth-and-moon work onto that rebased branch.

I took a video. Apologies if you get seasick; I don't have a proper setup for recording a phone screen!

Part 1:

You'll see from 00:07 that my thumb is practically covering the moon (a sentence not oft said).

https://user-images.githubusercontent.com/14055146/124994964-90640400-e03e-11eb-9652-0ec96ebc3501.mp4

Part 2:

At the start of this part, it's clear that my thumb totally obscures the earth (again, not oft said). Nice slide along the bottom of the screen, though.

https://user-images.githubusercontent.com/14055146/124995042-a671c480-e03e-11eb-8a8e-fc060c04da56.mp4

---

I had hoped to demonstrate whether or not the moon's circular orbit around the earth would result in having to adjust the earth upwards and downwards as I tracked horizontally across the page, but it's hard to tell for a few reasons:

1. My thumb is often obscuring the moon, making results inconclusive;
2. The moon becomes more obscured by my thumb as I track to the extremes of the page (as it tends to 45º either side, it slips under my thumb more);
3. Thumbs simply don't move perfectly horizontally in the first place.

So I think we'd best impose an offset to stop the moon being eclipsed. Considering that some users may have nail extensions (or simply long nails), there may even be a good argument to make it adjustable!

**Comment by birtles** [comment]
Thank you! That's excellent feedback! The videos are great.

Based on that I think I'd like to try the following approach:

* Firstly, make the earth a little bigger, e.g. 60px wide as I think you had already done actually.
* Make the moon stick to the earth when not dragging, i.e. its resting state.
* When the drag starts have the moon move up into position.
* Keep the current horizontal drift but probably drop the curvature from the vertical offset and have it just be a fixed vertical offset.
* Make the vertical offset significantly larger (possibly adjustable as you mention, but that can be post-MVP).
* Add a `transition: transform 0.2s` or so to the moon so that: (a) it animates from its resting position to its active position, (b) there is a bit of a delay as we adjust the drift (later we could even adjust its transform entirely independently of the earth so that when you move the earth quickly the moon trails behind).

**Comment by shirakaba** [comment]
> * Firstly, make the earth a little bigger, e.g. 60px wide as I think you had already done actually.

Sounds good.

> * Make the moon stick to the earth when not dragging, i.e. its resting state.
> * When the drag starts have the moon move up into position.

Sounds good. I agree that distinct resting and dragging states make a lot of sense. We could maybe even make the earth grow while dragging (the Reddit app does that with its Floating Action Button).

> * Keep the current horizontal drift but probably drop the curvature from the vertical offset and have it just be a fixed vertical offset.

I think this would be for the best, yes (as aesthetic as the idea of planets following an orbit is).

> * Make the vertical offset significantly larger (possibly adjustable as you mention, but that can be post-MVP).

Sounds good.

> Add a transition: transform 0.2s or so to the moon so that: (a) it animates from its resting position to its active position, (b) there is a bit of a delay as we adjust the drift (later we could even adjust its transform entirely independently of the earth so that when you move the earth quickly the moon trails behind).

Sounds good.

Not an MVP feature, but – with built-in CSS animations, could we possibly achieve a spring effect so that, when releasing the puck, the moon pleasantly bounces down to earth with a couple of diminishing thuds?

**Comment by birtles** [comment]
> Sounds good. I agree that distinct resting and dragging states make a lot of sense. We could maybe even make the earth grow beyond its base width while dragging (the Reddit app does that with its Floating Action Button). Actually, if it did grow, then it could maybe retain its current size of 50px at rest, too.

Oh, good idea. I've added that along with the other ideas to the `feat/puck-earth-and-moon` branch: https://github.com/shirakaba/10ten-ja-reader/commit/3c52329c86ca1e99bc3cb01ca09b4b1694a4d62a

I think the transition needs some tweaking but otherwise it's kind of neat.

> Not an MVP feature, but – with built-in CSS animations, could we possibly achieve a spring effect so that, when releasing the puck, the moon pleasantly bounces down to earth with a couple of diminishing thuds?

Oh yeah, this is definitely do-able. We might need to switch to Web Animations anyway if we can't fix the transition lag in which case doing this would might be a bit easier, I think.

**Comment by birtles** [comment]
https://user-images.githubusercontent.com/1232595/125040611-d4084d80-e0d2-11eb-84fc-aa9a2fa2587a.mp4

Here's how it looks in the Firefox simulator for me. I haven't tried with Safari/Chrome yet so it's possible the transitions between CSS variables don't work the same there.

**Comment by shirakaba** [comment]
The bouncing animation looks great:

https://user-images.githubusercontent.com/14055146/125053231-c637d580-e09c-11eb-85c0-fa71ecb18edb.mp4

General usage is far better than before:

https://user-images.githubusercontent.com/14055146/125053247-cc2db680-e09c-11eb-98b0-740022c1272d.mp4

**Comment by shirakaba** [comment]
Something’s occurred to me, which is somewhat evident even in the videos – it’s a strain to look up words at the edge of the screen. Not because the moon can’t reach it, but because you have to extend your thumb to its full extent to bring the earth and moon within reach. It’d be impossible to use on iPad without setting the tablet down on a surface and using one’s fingertips instead.

So perhaps the moon should project out rather further from the earth. Maybe being able to cover the whole screen distance with one thumb’s reach gives you too little control, but at the very least, more might be better. As it might all be subjective (short thumbs, long thumbs) maybe we’re in the realms of customisability being worth looking at.

**Comment by birtles** [comment]
Thanks for checking those updated patches. I think I see what you mean about the strain of looking up words at the far edge. At first thought the idea of further separating the puck position from lookup position has me a little concerned because:

(a) I wonder if it might be a little less intuitive to know where you need to put the puck in order to look up the word you're interested in,
(b) it probably decreases the safe area? (i.e. if you can look up the left-hand side of the screen by moving the puck on the right-hand side, what happens if you put the puck on the left-hand side? Presumably you can't? Or if you can, what effect would moving it have?)
(c) depending on which hand/digit/device you're using, the comfortable area for moving the puck might change

There might be something really clever we can do to fix all that based on where the puck started etc. but that would still leave the other problem you mentioned about reducing the level of control/precision.

Which is all to say I'm not sure but I agree it's probably worth experimenting with -- perhaps simply adding a slight magnification factor (e.g. 1.2 times) to the horizontal drift could make it easier? Otherwise, like you say, introducing customisability in the future might be our best bet.

**Comment by shirakaba** [comment]
Looks like making drift comfortable could become quite a rabbit hole. Maybe it should be left to after MVP.

In the meantime, I'm working on solving the blind spot at the bottom of the viewport (you can't look up anything that's at the bottom of the viewport, because the moon only goes upward).

My thought is that any time one stops dragging the earth, it reassesses whether the moon should sit atop it or below it. So you'd generally have the moon projecting from the top of the earth, but if you drop the earth down in the bottom extent of the viewport (provisionally that "bottom extent" will have a height of the height of the earth + the extent to which the moon extends out of it), then it'll flip the moon to the bottom of the earth for next time it's picked up. That way, you can look up things in the bottom extent of the viewport for a bit, then return the earth to somewhere more in the middle of the screen to resume its original behaviour of extending the moon from above.

<table>
<tr>
<td>
Moon above
</td>
<td>
Moon below
</td>
</tr>
<tr>
<td>
Screenshot 2021-07-10 at 13 57 35
</td>
<td>
Screenshot 2021-07-10 at 13 57 46
</td>
</tr>
</table>

**Comment by shirakaba** [comment]
> Here's how it looks in the Firefox simulator for me. I haven't tried with Safari/Chrome yet so it's possible the transitions between CSS variables don't work the same there.

Testing on macOS Firefox, I've found that, when dragging the earth across a wide page, it's clear that the horizontal drift of the moon doesn't look right. If you move your mouse reasonably quickly, you can see that the moon gets stuck at its initial x drift until you slow down a bit. This is alleviated entirely by removing the `transition: transform 0.1s` from the `.moon` class.

For reference, the `transition: transform 0.3s` on the `.earth` class doesn't seem to cause any problems at least.

I can take a video of this in action later.

**Comment by shirakaba** [comment]
Here's a recording of how the above/below earth & moon works in action. When the moon is above the earth, we use an offset of -60px as usual. When it's below the earth, we use an offset of 90px (the extra offset helps the moon not get covered by your thumb, which covers up more space below the earth than above it).

https://user-images.githubusercontent.com/14055146/125195407-5c126280-e24d-11eb-9ac6-cfed61506afd.mp4

I think it might be... better than nothing? The real problem is that the full-size URL bar (which excludes the bottom 112 px of the viewport when present) keeps reappearing as your pointer approaches the bottom 100 px or so. This means that you effectively still have a dead area, as you can't pull the earth towards the very bottom of the viewport without that URL bar sliding in to obstruct you.

The best we can do then, I think, is to add even more offset when the moon is below the earth, to let you reach words at the very bottom of the viewport without bringing the earth too close to the ~100px height zone that triggers the full-size URL bar to appear.

This may not catch all situations, but I hope the iPhone 11 Pro is pretty representative of the worst-case scenario for safe area. The only other significant device class might be the iPhone (Pro) Max.

**Comment by shirakaba** [comment]
PR here to get the ball rolling: https://github.com/shirakaba/10ten-ja-reader/pull/6

**Comment by birtles** [comment]
> > Here's how it looks in the Firefox simulator for me. I haven't tried with Safari/Chrome yet so it's possible the transitions between CSS variables don't work the same there.
> 
> Testing on macOS Firefox, I've found that, when dragging the earth across a wide page, it's clear that the horizontal drift of the moon doesn't look right. If you move your mouse reasonably quickly, you can see that the moon gets stuck at its initial x drift until you slow down a bit. This is alleviated entirely by removing the `transition: transform 0.1s` from the `.moon` class.

Right. That's the transition lag I was referring to. If it's not happening in other browsers then it sounds like a Firefox bug.

(There's an existing bug in Firefox when it comes to interrupting transitions that run on the compositor so I guess we're hitting that here. It doesn't apply to Web Animations, however so that's why I was wondering if we might eventually want to work around it with Web Animations. Alternatively, we might be able to force a style flush on the main thread to work around it.)

> It may be that there are also problems with the `.earth` transition on that I haven't been able to spot (i.e. does it track the pointer position convincingly), so if we were to turn one off, there might be sense in turning off both.

Right, the transition on the earth element only applies to the scale animation we apply to it. There's no transition on the actual positioning of the earth since we apply that (translate) transform to the container instead.

**Comment by birtles** [comment]
> ## -60px offsetY for above, 110px offsetY for below
> 
> The best we can do then, I think, is to add even more offset when the moon is below the earth, to let you reach words at the very bottom of the viewport without bringing the earth too close to the ~100px height zone that triggers the full-size URL bar to appear.

This looks great. I haven't looked at the PR yet so maybe you've already covered this, but I wonder if we can only use the 110px offset based on the absence/presence of an unsafe region at the bottom of the screen? i.e. use 90px for desktop browsers etc.

**Comment by shirakaba** [comment]
Closed in favour of the earth-and-moon approach.

**Pull request closed without merging**
