### PR TITLE
fix: popup constraints

### PR DESCRIPTION
**Pull request by shirakaba**
Addressing this regression for cursor users that I mentioned on Twitter:

> when the popup spawns for mouse users, it should be allowed to extend offscreen in the appropriate direction (if spawned on the left or right, then it should be able to extend downwards).

As mentioned in the TODO notes, at the time of this PR, we can't currently detect whether the popup was spawned by the puck or by the mouse. So for these below screenshots, I hard-coded the pointerType to 'cursor' to illustrate what functionality this PR restores.

<table>
<tr>
<td>Inline is still constrained<td/>
<td>Block is now unconstrained<td/>
</tr>
<tr>
<td>inline_constrained<td/>
<td>block_unconstrained<td/>
</tr>
</table>

### CODE REVIEW

**Comment by birtles** [comment]
Sorry, I think I'm completely misunderstanding this PR. I thought this was about not constraining the height when we have a mouse.

Looking at the patch it seems like in `getAboveOrBelowPosition`, we conditionally constrain the _width_ based on the pointer type but I would have expected it to be the _height_ we conditionally constrained?

In my understanding the behaviour we want is:

| layout | mouse                    | puck                     |
|--------|--------------------------|--------------------------|
| above  | constrain height + width | constrain height + width |
| below  | constrain width          | constrain height + width |
| left   | constrain width          | constrain height + width |
| right  | constrain width          | constrain height + width |

That is, we always want to constrain the width so it doesn't overlap the pointer / right edge of the page.

Furthermore, even when you have a mouse, if we position the popup above the pointer, we want to constrain its height so it doesn't cover the pointer (existing behaviour).

Or am I completely misunderstanding the issue?

**Comment by birtles** [comment]
(Everything else about the patch looks great though!)

**Comment by shirakaba** [comment]
> Looking at the patch it seems like in getAboveOrBelowPosition, we conditionally constrain the width based on the pointer type but I would have expected it to be the height we conditionally constrained?

Basically I was trying to restore the behaviour that I thought the original layout code had:

* When laying out popups on the left/right, the height would be unconstrained
* When laying out popups above/below, the width would be unconstrained

However, I may have misinterpreted it. Either way, I've pushed another commit that makes it behave like your table.

**Comment by birtles** [comment]
Thanks! Looks great!

I think the comment would make more sense to me in reverse, i.e. we don't constrain the height when using the cursor because you can scroll the window without dismissing the popup. Being able to scroll the popup is something we've yet to add.

I hope you don't mind if I make that change and then merge it.

**Pull request merged**
