### PR TITLE
feat: Puck moves via click-to-drag rather than hover

### PR DESCRIPTION
**Pull request by shirakaba**
Seems to work on both desktop and iOS (`touch-action: none` was the magic ingredient for the latter)!

## macOS

https://user-images.githubusercontent.com/14055146/124368534-cd548300-dc59-11eb-8d3e-a1a4d6d806f8.mp4

## iOS

https://user-images.githubusercontent.com/14055146/124368470-34be0300-dc59-11eb-947c-bd722c4f50c8.mp4

- [ ] Merge the PR that this is upstream of: https://github.com/shirakaba/10ten-ja-reader/pull/3

### CODE REVIEW

**Comment by birtles** [comment]
This looks great too.

I think we can merge this as-is but a couple of things I'd like to hear your thoughts on:

* When we get the `pointerdown` event, if we set `pointer-events: none` on the puck (and then restore it when we stop dragging), perhaps we wouldn't need to register the `mousemove` event handler?
* Do we actually need `capture: true` for the other events?
* Since `onWindowPointerUp` and `onWindowPointerCancel` just call `stopDraggingPuck`, maybe we should just register `stopDraggingPuck` as the event handler for those events?
* (Nit: Since `puckIsBeingDragged` is a member of the `RikaiPuck` class, perhaps it could be just `isDragging` or something?)

**Comment by shirakaba** [comment]
Think I'm out of time for tonight, so I'll get to these questions another day this week!

**Comment by birtles** [comment]
> Think I'm out of time for tonight, so I'll get to these questions another day this week!

Thanks! If you agree with the proposed changes, I'm happy to go ahead and try and make them.

**Comment by shirakaba** [comment]
> Thanks! If you agree with the proposed changes, I'm happy to go ahead and try and make them.

Sure thing, I'll get back to your points to keep the ball rolling.

> * When we get the `pointerdown` event, if we set `pointer-events: none` on the puck (and then restore it when we stop dragging), perhaps we wouldn't need to register the `mousemove` event handler?

This might kill support for Apple Pencil and other styluses (I'm just guessing), but those users don't need the Puck in the first place. We can go ahead with it, as it does reduce complexity and likely improves performance, too.

> * Do we actually need `capture: true` for the other events?

Perhaps not! Happy for it to be removed.

> * Since `onWindowPointerUp` and `onWindowPointerCancel` just call `stopDraggingPuck`, maybe we should just register `stopDraggingPuck` as the event handler for those events?

Sure thing.

> (Nit: Since `puckIsBeingDragged` is a member of the `RikaiPuck` class, perhaps it could be just `isDragging` or something?)

Fine by me. I flip-flopped a bit while choosing the name in the first place.

**Comment by birtles** [comment]
Great! Thanks for follow up on all that. Let me see what I can work out tomorrow.

**Comment by birtles** [comment]
Ok, I've made the simplifications suggested so I think we can merge this in now.

I don't _think_ toggling `pointer-events: none` on the puck should affect styluses etc. but we'll find out.

**Pull request merged**
